			<script type="text/javascript">
				var BROWSER_AJAX = "<?= BROWSER_AJAX; ?>";
				var BROWSER_IMAGES = "<?= BROWSER_IMAGES; ?>";
				var BROWSER_VOCALS = "<?= BROWSER_VOCALS; ?>";
				var BROWSER_PROFILES_IMAGES = "<?= BROWSER_PROFILES_IMAGES; ?>";
				var BROWSER_CGI = "<?= BROWSER_CGI; ?>";
				var BROWSER_SCENARIOS = "<?= BROWSER_SCENARIOS; ?>";
				var BROWSER_SCENARIOS_IMAGES = "<?= BROWSER_SCENARIOS_IMAGES; ?>";
				var BROWSER_SCENARIOS_MEDIA = "<?= BROWSER_SCENARIOS_MEDIA; ?>";
				var BROWSER_SCENARIOS_VOCALS = "<?= BROWSER_SCENARIOS_VOCALS; ?>";
				var BROWSER_VIDEO = "<?= BROWSER_VIDEO; ?>";
				var BROWSER_ROOT_FULL = "<?= BROWSER_ROOT_FULL; ?>";
								

				var AJAX_STATUS_FAIL = <?= AJAX_STATUS_FAIL; ?>;
				var AJAX_STATUS_OK = <?= AJAX_STATUS_OK; ?>;
				var AJAX_STATUS_LOGIN_FAIL = <?= AJAX_STATUS_LOGIN_FAIL; ?>;
				var SERVER_ADDR = "<?= SERVER_ADDR; ?>";
				var REMOTE_ADDR = "<?= REMOTE_ADDR; ?>";

			</script>